version: "3.2"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  application:
    image: siarheisaroka/application:latest
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      BG_COLOR: teal
      FAIL_FLAG: "false"
    container_name: application
    hostname: application
    ports:
      - "5000:5000"
    depends_on: 
            - mongo
    restart: always
